//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneSmallStep.Utility.Time {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OurResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OurResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OneSmallStep.Utility.Time.OurResources", typeof(OurResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} day.
        /// </summary>
        internal static string TimeOffsetDayLong_One {
            get {
                return ResourceManager.GetString("TimeOffsetDayLong_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} days.
        /// </summary>
        internal static string TimeOffsetDayLong_Other {
            get {
                return ResourceManager.GetString("TimeOffsetDayLong_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0}d.
        /// </summary>
        internal static string TimeOffsetDayShort_One {
            get {
                return ResourceManager.GetString("TimeOffsetDayShort_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0}d.
        /// </summary>
        internal static string TimeOffsetDayShort_Other {
            get {
                return ResourceManager.GetString("TimeOffsetDayShort_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} month.
        /// </summary>
        internal static string TimeOffsetMonthLong_One {
            get {
                return ResourceManager.GetString("TimeOffsetMonthLong_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} months.
        /// </summary>
        internal static string TimeOffsetMonthLong_Other {
            get {
                return ResourceManager.GetString("TimeOffsetMonthLong_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0}m.
        /// </summary>
        internal static string TimeOffsetMonthShort_One {
            get {
                return ResourceManager.GetString("TimeOffsetMonthShort_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0}m.
        /// </summary>
        internal static string TimeOffsetMonthShort_Other {
            get {
                return ResourceManager.GetString("TimeOffsetMonthShort_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1}.
        /// </summary>
        internal static string TimeOffsetTermJoin {
            get {
                return ResourceManager.GetString("TimeOffsetTermJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} year.
        /// </summary>
        internal static string TimeOffsetYearLong_One {
            get {
                return ResourceManager.GetString("TimeOffsetYearLong_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} years.
        /// </summary>
        internal static string TimeOffsetYearLong_Other {
            get {
                return ResourceManager.GetString("TimeOffsetYearLong_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0}y.
        /// </summary>
        internal static string TimeOffsetYearShort_One {
            get {
                return ResourceManager.GetString("TimeOffsetYearShort_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0}y.
        /// </summary>
        internal static string TimeOffsetYearShort_Other {
            get {
                return ResourceManager.GetString("TimeOffsetYearShort_Other", resourceCulture);
            }
        }
    }
}
