//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneSmallStep.Utility {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OurResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OurResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OneSmallStep.Utility.OurResources", typeof(OurResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:G4} Em.
        /// </summary>
        internal static string DistanceInExameters {
            get {
                return ResourceManager.GetString("DistanceInExameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:G4} Gm.
        /// </summary>
        internal static string DistanceInGigameters {
            get {
                return ResourceManager.GetString("DistanceInGigameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:G4} km.
        /// </summary>
        internal static string DistanceInKilometers {
            get {
                return ResourceManager.GetString("DistanceInKilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:G4} Mm.
        /// </summary>
        internal static string DistanceInMegameters {
            get {
                return ResourceManager.GetString("DistanceInMegameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:G4} m.
        /// </summary>
        internal static string DIstanceInMeters {
            get {
                return ResourceManager.GetString("DIstanceInMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:G4} Pm.
        /// </summary>
        internal static string DistanceInPetameters {
            get {
                return ResourceManager.GetString("DistanceInPetameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:G4} Tm.
        /// </summary>
        internal static string DistanceInTerameters {
            get {
                return ResourceManager.GetString("DistanceInTerameters", resourceCulture);
            }
        }
    }
}
